sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t nashmaniac/docker-react .

script:
  - docker run nashmaniac/docker-react npm build
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "docker-environment"
  bucket_name: "elasticbeanstalk-us-east-2-502747352996"
  bucket_path: "docker-react"
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  on:
    branch: master
